# Generated by Django 6.0.3 on 2026-03-12 15:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, default='N/A', max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, default='N/A', null=True)),
                ('location', models.CharField(max_length=100)),
                ('dob', models.CharField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'members',
                'managed': True,
            },
        ),
    ]
