# Generated by Django 6.0.3 on 2026-03-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_attendance_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='is_baptized',
            field=models.BooleanField(default=False),
        ),
    ]
