# Generated by Django 6.0.3 on 2026-03-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_members_is_baptized'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='marital_status',
            field=models.BooleanField(default=False),
        ),
    ]
