# Generated by Django 6.0.3 on 2026-04-07 14:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_members_marital_status_userprofiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('type', models.CharField(choices=[('Giving', 'Giving'), ('Tithe', 'Tithe'), ('Donation', 'Donation'), ('Benevolence', 'Benevolence'), ('Miscellaneous', 'Miscellaneous')], max_length=50)),
                ('purpose', models.TextField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Finance',
                'verbose_name_plural': 'Finances',
                'db_table': 'Finance',
                'managed': True,
            },
        ),
    ]
