# Generated by Django 6.0.3 on 2026-04-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_finance'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='category',
            field=models.CharField(choices=[('Giving', 'Giving'), ('Tithe', 'Tithe'), ('Donation', 'Donation'), ('Benevolence', 'Benevolence'), ('Miscellaneous', 'Miscellaneous')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=25, null=True),
        ),
    ]
