# Generated by Django 6.0.3 on 2026-04-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_finance_category_alter_finance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
