# Generated by Django 6.0.3 on 2026-04-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_finance_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
