# Generated by Django 6.0.3 on 2026-04-09 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_finance_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'managed': True, 'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendance'},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='members',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
        migrations.AddField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.members'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='non_registered',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='recorded_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='service_type',
            field=models.CharField(choices=[('sunday', 'Sunday Service'), ('midweek', 'Mid Week Service')], max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='attendance',
            table='Attendance',
        ),
    ]
