# Generated by Django 6.0.3 on 2026-04-09 14:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_alter_attendance_options_remove_attendance_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
