# Generated by Django 6.0.3 on 2026-04-11 12:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_attendance_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('full_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('phone_number', models.CharField(blank=True, default='N/A', null=True)),
                ('location', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('sunday', 'Sunday Service'), ('midweek', 'Mid Week Service')], max_length=100, null=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'visitors',
                'db_table': 'visitors',
                'managed': True,
            },
        ),
    ]
